FROM apache/nifi:latest
ADD --chown=nifi:nifi https://github.com/influxdata/nifi-influxdb-bundle/releases/download/v1.13.0/nifi-influx-database-nar-1.13.0.nar /opt/nifi/nifi-current/lib/
COPY --chown=nifi:nifi MQTT-to-InfluxDB.xml /opt/nifi/nifi-current/conf/templates/
EXPOSE 8443
ENTRYPOINT []